spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.100.1.116
    port: 6379
    #password:
server:
  context-path: /
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
wechat:
  # 微信授权 id
#  mpAppId: wx0465fe3767346d03
#  mpAppSecret: 98f3f91786611085871483c1b799aaf5
  mpAppId: wxaeb12c742cdc07aa
  mpAppSecret: 2254ff09bd0728befaa3672ee2104099
  openAppId: wxaeb12c742cdc07aa
  openAppSecret: 2254ff09bd0728befaa3672ee2104099
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath:  C:/Users/bangsun/Workspaces/eclipse/sell/src/main/resources/h5.p12
  notifyUrl: http://9dfd3bd7.ngrok.io/notify
  templateId:
    orderStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI
    payStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI

projectUrl:
  wechatMpAuthorize: http://9dfd3bd7.ngrok.io
  wechatOpenAuthorize: http://9dfd3bd7.ngrok.io
  sell: http://localhost:8080
logging:
  level:
    com.gexf.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml





